swagger: "2.0"
info:
  version: "1.0"
  title: "Dovecot Anti-Abuse Shield"
  description: "An API to the Dovecot Anti-Abuse Shield to prevent brute-force and abuse of mail systems"
  contact:
    name: "Dovecot Oy"
  license:
    name: "GPL2"
    url: http://github.com/PowerDNS/weakforced/master/LICENSE
host: "doesnotexist.dovecot.fi"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /?command=report:
    post:
      description: "Creates a new report about a login (successful or unsuccessful)"
      operationId: "report"
      produces:
        - "application/json"
      parameters:
        - name: "LoginTupleReport"
          in: body
          description: "Login Tuple for report command"
          required: true
          schema:
            $ref: "#/definitions/LoginTupleReport"
      responses:
        "200":
          description: "report reponse"
          schema:
            type: object
            required:
              - status
            properties:
              status:
                type: string
            example:
              status: ok
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /?command=allow:
    post:
      description: "Query whether a login should be allowed"
      operationId: "allow"
      produces:
        - "application/json"
      parameters:
        - name: "LoginTupleAllow"
          in: body
          description: "Login Tuple for allow command"
          required: true
          schema:
            $ref: "#/definitions/LoginTupleAllow"
      responses:
        "200":
          description: "report reponse"
          schema:
            type: object
            required:
              - status
              - msg
            properties:
              status:
                type: integer
              msg:
                type: string
            example:
              status: -1
              msg: "Too many failed passwords"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /?command=reset:
    post:
      description: "Reset the stats for an IP and/or login"
      operationId: "reset"
      produces:
        - "application/json"
      parameters:
        - name: "Reset"
          in: body
          description: "Provide IP and/or login"
          required: true
          schema:
            $ref: "#/definitions/ResetStatsParams"
      responses:
        "200":
          description: "reset reponse"
          schema:
            type: object
            required:
              - status
            properties:
              status:
                type: string
              msg:
                type: string
            example:
              status: ok
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /?command=ping:
    get:
      description: "Ping the server to ensure it is operational"
      operationId: "ping"
      produces:
        - "application/json"
      responses:
        "200":
          description: "ping reponse"
          schema:
            type: object
            required:
              - status
            properties:
              status:
                type: string
            example:
              status: ok
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /?command=getBL:
    get:
      description: "Get the list of all blacklisted IPs and/or Logins"
      operationId: "getBL"
      produces:
        - "application/json"
      responses:
        "200":
          description: "getBL reponse"
          schema:
            $ref: "#/definitions/BLResponse"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /?command=getDBStats:
    post:
      description: "Get the db stats for an IP and/or login"
      operationId: "getDBStats"
      produces:
        - "application/json"
      parameters:
        - name: "GetDBStats"
          in: body
          description: "Provide IP and/or login"
          required: true
          schema:
            $ref: "#/definitions/ResetStatsParams"
      responses:
        "200":
          description: "getDBStats reponse"
          schema:
            $ref: "#/definitions/DBStatsResponse"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
definitions:
  LoginTupleReport:
    required:
      - login
      - remote
      - pwhash
      - success
    example:
      login: joe.bloggs
      remote: 192.168.1.2
      pwhash: cc04
      success: true
    properties:
      login:
        type: string
      remote:
        type: string
      pwhash:
        type: string
      success:
        type: string
      policy_reject:
        type: boolean
      attrs:
        $ref: "#/definitions/LTAttrs" 
  LTAttrs:
    type: object
    properties:
      attr_name_single_value:
        type: string
      attr_name multi_value:
          type: array
          items:
            type: string
    example:
      attr1: value1
      attr2: value2
      attr3: [ value3, value4 ]
  LoginTupleAllow:
    required:
      - login
      - remote
      - pwhash
    properties:
      login:
        type: string
      remote:
        type: string
      pwhash:
        type: string
      attrs:
        $ref: "#/definitions/LTAttrs" 
    example:
      login: joe.bloggs
      remote: 192.168.1.2
      pwhash: cc04
      success: true
      attrs: { "foo":"bar" }
  ResetStatsParams:
    properties:
      ip:
        type: string
      login:
        type: string
    example:
      ip: 127.0.0.1
  Error:
    required:
      - status
      - reason
    properties:
      status:
        type: string
      reason:
        type: string
    example:
      status: failure
      reason: Unauthorized
  BLResponse:
    type: object
    properties:
      bl_entries:
        type: array
        items:
          $ref: "#/definitions/BLArray"
  BLArray:
    type: object
    properties:
      ip:
        $ref: "#/definitions/BLEntry"
      login:
        $ref: "#/definitions/BLEntry"
      iplogin:
        $ref: "#/definitions/BLEntry"
  BLEntry:
    type: array
    items:
      type: object
      properties:
        key_name:
          type: string
        expiration:
          type: string
        reason:
          type: string
      example:
        login: joe.bloggs
        expiration: 2002-Jan-01 10:00:01
        reason: Too many invalid login attempts from greylisted countries
  DBStatsResponse:
    type: object
    required:
      - key_name
      - blacklisted
      - stats
    properties:
      key_name:
        type: string
      blacklisted:
        type: boolean
      stats:
        $ref: "#/definitions/DBStatsEntry"
  DBStatsEntry:
    type: object
    properties:
      db_name:
        $ref: "#/definitions/DBStatsFields"
  DBStatsFields:
    type: object
    properties:
      field_name:
        type: integer
    example:
      countLogins: 239
      diffPassword: 10
